# Import relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
import nltk
import string
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [3]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [4]:
df1 = pd.read_csv('feature_set.csv')

In [5]:
df1.drop('Unnamed: 0',axis=1,inplace=True)

In [6]:
df1.head()

transformed_posts  ...  nrc_vad
0  http enfp intj moment http sportscent top ten ...  ...        0
1  find lack post alarm sex bore posit often exam...  ...        1
2  one http cours say know bless curs absolut pos...  ...        1
3  intp enjoy convers day esoter gab natur univer...  ...        0
4  fire anoth silli misconcept approach logic go ...  ...        0

[5 rows x 9 columns]

In [7]:
df2 = pd.read_csv('label_set.csv')

In [8]:
df2.head()

Unnamed: 0  I-E  N-S  T-F  J-P
0           0    0    0    1    0
1           1    1    0    0    1
2           2    0    0    0    1
3           3    0    0    0    0
4           4    1    0    0    0

In [9]:
df2.drop('Unnamed: 0',axis=1,inplace=True)

In [10]:
df2.head()

I-E  N-S  T-F  J-P
0    0    0    1    0
1    1    0    0    1
2    0    0    0    1
3    0    0    0    0
4    1    0    0    0

In [11]:
tfidf = TfidfVectorizer(max_features=10000)
vectorised_posts = tfidf.fit_transform(df1['transformed_posts']).toarray()

In [12]:
vectorised_posts.shape

(8675, 10000)

In [13]:
y_ie = df2['I-E'].values
y_ns = df2['N-S'].values
y_tf = df2['T-F'].values
y_jp = df2['J-P'].values

In [ ]:

type(y_ie)

numpy.ndarray

In [23]:
from sklearn.model_selection import train_test_split
X_train_ie,X_test_ie,y_train_ie,y_test_ie = train_test_split(X,y_ie,test_size=0.33,random_state=2)
X_train_ns,X_test_ns,y_train_ns,y_test_ns = train_test_split(X,y_ns,test_size=0.33,random_state=2)
X_train_tf,X_test_tf,y_train_tf,y_test_tf = train_test_split(X,y_tf,test_size=0.33,random_state=2)
X_train_jp,X_test_jp,y_train_jp,y_test_jp = train_test_split(X,y_jp,test_size=0.33,random_state=2)

ValueError: ignored

In [ ]:
type(df1['ttr'][0])

numpy.float64

In [ ]:
type(df1['vectorised_col'][0])

numpy.ndarray

In [ ]:
X_train_ie

num_words  num_sentences  http_per_comment  words_per_comment  \
6886       1175             64              0.06              20.10   
1892       1655             94              0.02              28.64   
7228       1868            103              0.00              31.44   
2667       1918            143              0.00              30.96   
3591       1777            105              0.04              30.26   
...         ...            ...               ...                ...   
1099        703             23              0.02              12.48   
2514       1303            110              0.00              21.86   
6637       1597             80              0.00              27.00   
2575       1506             98              0.00              25.18   
7336        852             32              0.72              10.96   

      emoticons_per_comment       ttr  nrc_emotion  nrc_vad  \
6886                      0  0.089068       14.625        1   
1892                      0  0.084172       15.875        0   
7228                      0  0.083363       26.375        1   
2667                      0  0.088615       23.250        3   
3591                      0  0.079279       25.625        6   
...                     ...       ...          ...      ...   
1099                      0  0.099370        8.375        1   
2514                      0  0.104001       25.875        1   
6637                      0  0.091440       23.000        1   
2575                      0  0.086852       14.500       13   
7336                      0  0.077706        8.375        1   

                                         vectorised_col  
6886  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1892  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
7228  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2667  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3591  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
...                                                 ...  
1099  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2514  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
6637  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2575  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
7336  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[5812 rows x 9 columns]

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [15]:
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

In [16]:
clfs = {
    'KN' : knc, 
    'NB': mnb, 
    'DT': dtc, 
    'LR': lrc, 
    'RF': rfc, 
    'ETC': etc,
    'xgb':xgb
}

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    cm = confusion_matrix(y_test,y_pred)
    return accuracy,precision,cm

In [ ]:
train_classifier(mnb,X_train_ie,y_train_ie,X_test_ie,y_test_ie)

In [18]:
X1 = vectorised_posts

In [ ]:
X1[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [19]:
from sklearn.model_selection import train_test_split
X1_train,X1_test,y_train_ie,y_test_ie = train_test_split(X1,y_ie,test_size=0.33,random_state=2)

In [ ]:
train_classifier(mnb,X1_train,y_train_ie,X1_test,y_test_ie)

(0.773663988822913,
 0.8571428571428571,
 array([[2209,    1],
        [ 647,    6]], dtype=int64))

In [ ]:
train_classifier(lrc,X1_train,y_train_ie,X1_test,y_test_ie)

(0.851903597624869,
 0.7681498829039812,
 array([[2111,   99],
        [ 325,  328]], dtype=int64))

In [ ]:
train_classifier(xgb,X1_train,y_train_ie,X1_test,y_test_ie)

In [ ]:
X2_train,X2_test,y_train_ns,y_test_ns = train_test_split(X1,y_ns,test_size=0.33,random_state=2)

In [ ]:
train_classifier(lrc,X2_train,y_train_ns,X2_test,y_test_ns)

(0.9109325881942019,
 0.7864583333333334,
 array([[2457,   41],
        [ 214,  151]], dtype=int64))

In [ ]:
train_classifier(xgb,X2_train,y_train_ns,X2_test,y_test_ns)

D:\16 personality analysis\personality\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[14:50:11] WARNING: ..\src\learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


(0.9070904645476773,
 0.728110599078341,
 array([[2439,   59],
        [ 207,  158]], dtype=int64))

In [20]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
    
    current_accuracy,current_precision, current_cm = train_classifier(clf, X1_train,y_train_ie,X1_test,y_test_ie)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Confusion Matrix - \n", current_cm)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For  KN
Accuracy -  0.7995110024449877
Precision -  0.5916473317865429
Confusion Matrix - 
 [[2034  176]
 [ 398  255]]
For  NB
Accuracy -  0.773663988822913
Precision -  0.8571428571428571
Confusion Matrix - 
 [[2209    1]
 [ 647    6]]
For  DT
Accuracy -  0.829898707649319
Precision -  0.6985645933014354
Confusion Matrix - 
 [[2084  126]
 [ 361  292]]
For  LR
Accuracy -  0.851903597624869
Precision -  0.7681498829039812
Confusion Matrix - 
 [[2111   99]
 [ 325  328]]
For  RF
Accuracy -  0.779252532308767
Precision -  0.8888888888888888
Confusion Matrix - 
 [[2207    3]
 [ 629   24]]
For  ETC
Accuracy -  0.77645826056584
Precision -  0.782608695652174
Confusion Matrix - 
 [[2205    5]
 [ 635   18]]
For  xgb
Accuracy -  0.8515543136570032
Precision -  0.796875
Confusion Matrix - 
 [[2132   78]
 [ 347  306]]


In [21]:
performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)

In [22]:
performance_df

Algorithm  Accuracy  Precision
4        RF  0.779253   0.888889
1        NB  0.773664   0.857143
6       xgb  0.851554   0.796875
5       ETC  0.776458   0.782609
3        LR  0.851904   0.768150
2        DT  0.829899   0.698565
0        KN  0.799511   0.591647

In [23]:
X2_train,X2_test,y_train_ns,y_test_ns = train_test_split(X1,y_ns,test_size=0.33,random_state=2)

In [24]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
    
    current_accuracy,current_precision, current_cm = train_classifier(clf, X2_train,y_train_ns,X2_test,y_test_ns)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Confusion Matrix - \n", current_cm)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For  KN
Accuracy -  0.8805448829898708
Precision -  0.5696969696969697
Confusion Matrix - 
 [[2427   71]
 [ 271   94]]
For  NB
Accuracy -  0.8721620677610897
Precision -  0.0
Confusion Matrix - 
 [[2497    1]
 [ 365    0]]
For  DT
Accuracy -  0.8903248340901153
Precision -  0.606694560669456
Confusion Matrix - 
 [[2404   94]
 [ 220  145]]
For  LR
Accuracy -  0.9109325881942019
Precision -  0.7864583333333334
Confusion Matrix - 
 [[2457   41]
 [ 214  151]]
For  RF
Accuracy -  0.8739084876004192
Precision -  1.0
Confusion Matrix - 
 [[2498    0]
 [ 361    4]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


For  ETC
Accuracy -  0.8725113517289557
Precision -  0.0
Confusion Matrix - 
 [[2498    0]
 [ 365    0]]
For  xgb
Accuracy -  0.9046454767726161
Precision -  0.8066666666666666
Confusion Matrix - 
 [[2469   29]
 [ 244  121]]


In [25]:
performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)
performance_df

Algorithm  Accuracy  Precision
4        RF  0.873908   1.000000
6       xgb  0.904645   0.806667
3        LR  0.910933   0.786458
2        DT  0.890325   0.606695
0        KN  0.880545   0.569697
1        NB  0.872162   0.000000
5       ETC  0.872511   0.000000

In [26]:
X3_train,X3_test,y_train_tf,y_test_tf = train_test_split(X1,y_tf,test_size=0.33,random_state=2)

In [27]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
    
    current_accuracy,current_precision, current_cm = train_classifier(clf, X3_train,y_train_tf,X3_test,y_test_tf)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Confusion Matrix - \n", current_cm)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For  KN
Accuracy -  0.6894865525672371
Precision -  0.6542185338865837
Confusion Matrix - 
 [[ 555  750]
 [ 139 1419]]
For  NB
Accuracy -  0.7645826056584003
Precision -  0.7190287413280476
Confusion Matrix - 
 [[ 738  567]
 [ 107 1451]]
For  DT
Accuracy -  0.7394341599720573
Precision -  0.8103975535168195
Confusion Matrix - 
 [[1057  248]
 [ 498 1060]]
For  LR
Accuracy -  0.8501571777855397
Precision -  0.8570524984187223
Confusion Matrix - 
 [[1079  226]
 [ 203 1355]]
For  RF
Accuracy -  0.7635347537548026
Precision -  0.7648827420324714
Confusion Matrix - 
 [[ 914  391]
 [ 286 1272]]
For  ETC
Accuracy -  0.7579462102689487
Precision -  0.7431141090500281
Confusion Matrix - 
 [[ 848  457]
 [ 236 1322]]
For  xgb
Accuracy -  0.8169752008382816
Precision -  0.8292993630573249
Confusion Matrix - 
 [[1037  268]
 [ 256 1302]]


In [28]:
performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)
performance_df

Algorithm  Accuracy  Precision
3        LR  0.850157   0.857052
6       xgb  0.816975   0.829299
2        DT  0.739434   0.810398
4        RF  0.763535   0.764883
5       ETC  0.757946   0.743114
1        NB  0.764583   0.719029
0        KN  0.689487   0.654219

In [29]:
X4_train,X4_test,y_train_jp,y_test_jp = train_test_split(X1,y_jp,test_size=0.33,random_state=2)

In [31]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
    
    current_accuracy,current_precision, current_cm = train_classifier(clf, X4_train,y_train_jp,X4_test,y_test_jp)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Confusion Matrix - \n", current_cm)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

For  KN
Accuracy -  0.703807195249738
Precision -  0.7439775910364146
Confusion Matrix - 
 [[ 687  457]
 [ 391 1328]]
For  NB
Accuracy -  0.6157876353475376
Precision -  0.6101815592737629
Confusion Matrix - 
 [[  49 1095]
 [   5 1714]]
For  DT
Accuracy -  0.7268599371288857
Precision -  0.7295443410093092
Confusion Matrix - 
 [[ 592  552]
 [ 230 1489]]
For  LR
Accuracy -  0.8082431016416346
Precision -  0.8072478991596639
Confusion Matrix - 
 [[ 777  367]
 [ 182 1537]]
For  RF
Accuracy -  0.6748166259168704
Precision -  0.6661045531197302
Confusion Matrix - 
 [[ 352  792]
 [ 139 1580]]
For  ETC
Accuracy -  0.6604959832343695
Precision -  0.6521384928716905
Confusion Matrix - 
 [[ 290  854]
 [ 118 1601]]
For  xgb
Accuracy -  0.7785539643730353
Precision -  0.7727501256913022
Confusion Matrix - 
 [[ 692  452]
 [ 182 1537]]


In [32]:
performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)
performance_df

Algorithm  Accuracy  Precision
3        LR  0.808243   0.807248
6       xgb  0.778554   0.772750
0        KN  0.703807   0.743978
2        DT  0.726860   0.729544
4        RF  0.674817   0.666105
5       ETC  0.660496   0.652138
1        NB  0.615788   0.610182

In [34]:
lr_ie = LogisticRegression(solver='liblinear', penalty='l1')

In [35]:
train_classifier(lr_ie,X1_train,y_train_ie,X1_test,y_test_ie)

(0.851903597624869, 0.7681498829039812, array([[2111,   99],
        [ 325,  328]]))

In [36]:
lr_ns = LogisticRegression(solver='liblinear', penalty='l1')

In [37]:
train_classifier(lr_ns,X2_train,y_train_ns,X2_test,y_test_ns)

(0.9109325881942019, 0.7864583333333334, array([[2457,   41],
        [ 214,  151]]))

In [38]:
lr_tf = LogisticRegression(solver='liblinear', penalty='l1')

In [39]:
train_classifier(lr_tf,X3_train,y_train_tf,X3_test,y_test_tf)

(0.8501571777855397, 0.8570524984187223, array([[1079,  226],
        [ 203, 1355]]))

In [40]:
lr_jp = LogisticRegression(solver='liblinear', penalty='l1')

In [70]:
lr_jp.fit(X4_train,y_train_jp)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l1',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [71]:
y_pred_jp = clf.predict(X4_test)
accuracy = accuracy_score(y_test_jp,y_pred_jp)
precision = precision_score(y_test_jp,y_pred_jp)

In [72]:
print(accuracy,precision)

0.7785539643730353 0.7727501256913022


In [41]:
train_classifier(clf, X4_train,y_train_jp,X4_test,y_test_jp)

(0.7785539643730353, 0.7727501256913022, array([[ 692,  452],
        [ 182, 1537]]))

In [44]:
import pickle
with open('model_ie.pickle','wb') as f:
  pickle.dump(lr_ie,f)

In [45]:
with open('model_ns.pickle','wb') as f:
  pickle.dump(lr_ns,f)

In [46]:
with open('model_tf.pickle','wb') as f:
  pickle.dump(lr_tf,f)

In [74]:
with open('model_jp.pickle','wb') as f:
  pickle.dump(lr_jp,f)

In [51]:
with open('vectorizer.pickle','wb') as f1:
  pickle.dump(tfidf,f1)

In [75]:
EorI_model = pickle.load(open('model_ie.pickle', 'rb'))
SorN_model = pickle.load(open("model_ns.pickle", 'rb'))
TorF_model = pickle.load(open("model_tf.pickle", 'rb'))
JorP_model = pickle.load(open("model_jp.pickle", 'rb'))

In [52]:
tfidf = pickle.load(open('vectorizer.pickle', 'rb'))

In [53]:
def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
    text = y[:]
    y.clear()
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
    text = y[:]
    y.clear()
    
    for i in text:
        y.append(ps.stem(i))
    
            
    return " ".join(y)

In [54]:
text = 'I plugged the data into tableau to see how the different features or how various mathematical formulas relate to the Weight. Once I had a few that didn’t have a wide distribution, I just started trying different models, even ones we hadn’t gone over yet. There are a LOT of regression models. I do not like this try everything method, it’s inefficient and illogical.'

In [56]:
from nltk.corpus import stopwords
import string
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [58]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [59]:
transformed_text = transform_text(text)
transformed_text

'plug data tableau see differ featur variou mathemat formula relat weight wide distribut start tri differ model even one gone yet lot regress model like tri everyth method ineffici illog'

In [61]:
vector_input = tfidf.transform([transformed_text])

In [76]:
EorI_model = pickle.load(open('model_ie.pickle', 'rb'))
SorN_model = pickle.load(open("model_ns.pickle", 'rb'))
TorF_model = pickle.load(open("model_tf.pickle", 'rb'))
JorP_model = pickle.load(open("model_jp.pickle", 'rb'))

In [77]:
result1 = EorI_model.predict(vector_input)[0]
result2 = SorN_model.predict(vector_input)[0]
result3 = TorF_model.predict(vector_input)[0]
result4 = JorP_model.predict(vector_input)[0]

In [79]:
print(result1,result2,result3,result4)

0 0 0 1
